### PR TITLE
Fix custom dimensions tab in free

### LINKED ISSUE #351: Custom dimensions tab missing in free after settings api update

### PR DESCRIPTION
**Pull request by Petervw**
Fixes #351

### CODE REVIEW

File: admin/class-admin.php [hunk 1]
```diff
@@ -133,15 +133,31 @@ public function add_action_links( $links ) {
...
 	 * Adds some promo text for the premium plugin on the custom dimensions tab.
 	 */
 	public function premium_promo() {
 		echo '<div class="ga-promote">';
-		echo '<p>';
-		printf( __( 'If you want to track custom dimensions like page views per author or post type, you should upgrade to the %1$spremium version of Google Analytics by Yoast%2$s.', 'google-analytics-for-wordpress' ), '<a href="https://yoast.com/wordpress/plugins/google-analytics/#utm_medium=text-link&utm_source=gawp-config&utm_campaign=wpgaplugin&utm_content=custom_dimensions_tab">', '</a>' );
-		echo ' ';
-		_e( 'This will also give you email access to the support team at Yoast, who will provide support on the plugin 24/7.', 'google-analytics-for-wordpress' );
-		echo '</p>';
+			echo '<p>';
```
Comment (omarreiss) [inline admin/class-admin.php]: @Petervw why did you indent this?

Comment (Petervw) [inline admin/class-admin.php]: HTML it is.

**Comment by Petervw** [comment]
@omarreiss I've moved the message to a separate view. Much cleaner now :)
